### PR TITLE
Added user_friend_request_accept

### PR DESCRIPTION
**Pull request by haydara**
Added the ability to accept friend request

### CODE REVIEW

**Comment by lianglee** [comment]
Already exists
https://www.opensource-socialnetwork.org/webservices/view/3574/user-send-friend-request

**Comment by haydara** [comment]
This is to accept the request sent by https://www.opensource-socialnetwork.org/webservices/view/3574/user-send-friend-request

**Comment by lianglee** [comment]
This will also accept it if you read the page. Basically accepting request
is same as send request.

**Comment by haydara** [comment]
Thanks

**Pull request closed without merging**
